[package]
name = "password_generator"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli-clipboard = "0.2.0"
passwords = "1.1.5"
clearscreen = "1.0.7"